workspace:
  base: /go
  path: src/github.com/drone-plugins/drone-docker
pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
    commands:
      # Disabled: main.go:99: cli.StringSlice composite literal uses unkeyed fields
      # - go vet
      - go test -cover -coverprofile=coverage.out
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER" -a -tags netgo

  latest:
    image: plugins/docker
    repo: plugins/docker
    tags: [ "latest", "1.2", "1" ]
    when:
      branch: master
      event: push

plugin:
  name: Docker
  desc: Build and publish images to a Docker registry
  type: publish
  image: plugins/docker
  labels:
    - docker
    - image
    - container
